import { WorldTemplate } from '../worldProfile/worldTemplateTypes';
import { WorldProfile } from '../worldProfile/worldProfileTypes';
import {
  WorldSnapshot,
  Character,
  Location,
  LocationEdge,
  Organization,
  WorldFact,
  HiddenTruth,
  Seed,
  Event,
} from '../../types';

export function createCyberpunkWorldTemplate(worldId: string): WorldTemplate {
  const profile: WorldProfile = {
    world_id: worldId,
    genre: 'CYBERPUNK',
    genre_version: 1,
    display_name: '新九龙霓虹界',
    world_description: '高耸入云的巨企大厦，永不停息的酸雨，深巷中的霓虹灯牌与黑客深网。',
    cosmology: '物理现实与深层赛博网络（DeepNet）构成的双重空间。',
    power_system: '义体植入、网络入侵、高阶AI算力、战斗芯片。',
    social_structure: '跨国巨企、地下义体帮派、黑客义佣、执法安保公司。',
    economy_system: '欧罗币（EuroDollar）与加密数据货币。',
    geography_style: '霓虹雨夜街区、巨企总部高塔、黑客地下吧、垃圾回收下水道。',
    currency_name: '欧元',
    energy_name: '电力算力',
    narrator_role: '深网监控AI',
    narration_style: '冷硬赛博、科技术语、黑客俚语。',
    profession_lexicon: ['黑客', '义佣', '黑医', '巨企特工', '街头混混', '网路浪客'],
    faction_lexicon: ['荒坂重工', '新九龙黑客帮', '夜巡安保公司'],
    location_lexicon: ['霓虹暗巷', '深网吧', '荒坂高塔', '黑市义体诊所'],
    creature_lexicon: ['战斗流浪者', 'AI流窜体', '强化义体狂暴者'],
    item_lexicon: ['欧元', '黑客接入仓', '单分子线', '神经药剂', '高频振动刃'],
    allowed_concepts: [
      '赛博', '黑客', '义体', '巨企', '欧元', '深网', '霓虹', '芯片', '义佣'
    ],
    forbidden_concepts: [
      '灵石', '灵力', '宗门', '坊市', '散修', '元婴', '筑基', '飞剑', '乾坤袋',
      '雇佣兵酒馆', '魔导师', '骑士团', '黑麦啤酒', '精金战锤', '核辐射废土'
    ],
    default_player_origin: '自由黑客义佣',
    default_player_title: '潜网者',
    created_at_epoch: 1,
    updated_at_epoch: 1,
  };

  const snapshot: WorldSnapshot = {
    id: worldId,
    epoch: 1,
    created_at: new Date().toISOString(),
    world_name: '新九龙霓虹界',
    world_description: '高耸入云的巨企大厦，永不停息的酸雨，深巷中的霓虹灯牌与黑客深网。',
    world_creation_state: 'CREATED',
    seed: 5555,
    world_facts_count: 3,
    characters_count: 3,
    organizations_count: 2,
    locations_count: 3,
    active_seeds_count: 2,
    frozen_objects_count: 0,
    completed_epochs: 0,
  };

  const locations: Location[] = [
    {
      id: 'loc-neon-bar',
      world_id: worldId,
      name: '霓虹暗巷深网吧',
      type: 'TOWN',
      description: '雨夜中闪烁着粉紫色霓虹灯牌的地下酒吧，地下黑客与潜网义佣在此接单。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-arasaka-tower'],
      population: 30,
      population_trend: 'STABLE',
      economy: { primary_industry: 'TRADE', wealth_level: 'MEDIUM', trade_volume: 'ACTIVE' },
      security: { crime_rate: 0.6, guard_presence: 'LOW', danger_level: 'SAFE' },
      active_events: [],
      features: ['深网接入节点', '黑市数据交易'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-arasaka-tower',
      world_id: worldId,
      name: '荒坂重工高塔',
      type: 'CITY',
      description: '矗立在云层中的钢铁与玻璃巨塔，周围全息广告牌闪烁不休，守备极其严密。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-neon-bar', 'loc-cyber-clinic'],
      population: 2000,
      population_trend: 'STABLE',
      economy: { primary_industry: 'INDUSTRY', wealth_level: 'WEALTHY', trade_volume: 'HIGH' },
      security: { crime_rate: 0.1, guard_presence: 'HIGH', danger_level: 'SAFE' },
      active_events: [],
      features: ['巨企数据库', '自动安保机甲'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-cyber-clinic',
      world_id: worldId,
      name: '老章黑市义体诊所',
      type: 'TOWN',
      description: '隐蔽在暗巷深处的无牌诊所，老章在这里改装军规级神经义体。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-arasaka-tower'],
      population: 15,
      population_trend: 'STABLE',
      economy: { primary_industry: 'TRADE', wealth_level: 'MEDIUM', trade_volume: 'MEDIUM' },
      security: { crime_rate: 0.5, guard_presence: 'NONE', danger_level: 'SAFE' },
      active_events: [],
      features: ['义体改造', '黑市神经药剂'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const locationEdges: LocationEdge[] = [
    {
      id: 'edge-cp-1',
      world_id: worldId,
      from_location_id: 'loc-neon-bar',
      to_location_id: 'loc-arasaka-tower',
      distance: 2.0,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-cp-2',
      world_id: worldId,
      from_location_id: 'loc-arasaka-tower',
      to_location_id: 'loc-neon-bar',
      distance: 2.0,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-cp-3',
      world_id: worldId,
      from_location_id: 'loc-arasaka-tower',
      to_location_id: 'loc-cyber-clinic',
      distance: 1.5,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-cp-4',
      world_id: worldId,
      from_location_id: 'loc-cyber-clinic',
      to_location_id: 'loc-arasaka-tower',
      distance: 1.5,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
  ];

  const characters: Character[] = [
    {
      id: 'pc-player',
      world_id: worldId,
      type: 'PC',
      name: '零点',
      title: '潜网义佣',
      species: '人类（半义体）',
      age: 24,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-neon-bar',
      goal: { primary: '黑入荒坂重工深层服务器窃取原型芯片' },
      personality: { trait: '冷酷警惕', tone: '言简意赅' },
      fear: { primary: '神经系统被杀手程序烧毁' },
      attributes: { hp: 100, mp: 80, strength: 10, dexterity: 15, intelligence: 16, charisma: 9 },
      skills: ['深网入侵', '单分子线割切'],
      resources: { 欧元: 300 },
      inventory: ['黑客接入仓', '单分子线', '神经抑制剂'],
      knowledge: ['新九龙黑客暗号'],
      memory: ['在深网吧收到了一份高额匿名委托。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在网吧角落调试黑客接入仓' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-clinic-zhang',
      world_id: worldId,
      type: 'NPC',
      name: '老章',
      title: '黑市义体医生',
      species: '人类',
      age: 50,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-cyber-clinic',
      goal: { primary: '收集军规级义体碎片' },
      personality: { trait: '古怪执着', tone: '沙哑低沉' },
      fear: { primary: '诊所被安保部队查封' },
      attributes: { hp: 90, mp: 50, strength: 9, dexterity: 14, intelligence: 15, charisma: 10 },
      skills: ['神经外科', '义体改装'],
      resources: { 欧元: 800 },
      inventory: ['手术激光刀', '神经稳定剂'],
      knowledge: ['军规义体后门电路'],
      memory: ['为零点植入了第二代黑客接口。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在诊所内维修高频振动刀' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-corp-agent',
      world_id: worldId,
      type: 'NPC',
      name: 'V-87',
      title: '荒坂反黑客特工',
      species: '人类（高阶植入）',
      age: 31,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-arasaka-tower',
      goal: { primary: '消灭所有试图入侵高塔的黑客' },
      personality: { trait: '冰冷机械', tone: '毫无感情' },
      fear: { primary: '未能完成巨企任务被格式化' },
      attributes: { hp: 180, mp: 120, strength: 15, dexterity: 16, intelligence: 14, charisma: 8 },
      skills: ['冰墙防御', '热能冲锋枪打靶'],
      resources: { 欧元: 2000 },
      inventory: ['军规冲锋枪', '荒坂安保卡'],
      knowledge: ['巨企内部防火墙结构'],
      memory: ['检测到新九龙深网频道的异常数据流。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在高塔安保中心监控深网' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const organizations: Organization[] = [
    {
      id: 'org-arasaka',
      world_id: worldId,
      name: '荒坂重工',
      type: 'CORPORATION',
      description: '控制新九龙绝大多数算力与安保的跨国巨企。',
      headquarters_id: 'loc-arasaka-tower',
      territory_ids: ['loc-arasaka-tower'],
      leader_id: 'npc-corp-agent',
      member_ids: ['npc-corp-agent'],
      resources: { 欧元: 1000000 },
      goals: ['垄断深网数据，推行全民脑机协议'],
      projects: ['测试原型神经控制芯片'],
      relationships: [],
      reputation: { level: 'RENOWNED', points: 95 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-hackers',
      world_id: worldId,
      name: '新九龙黑客联盟',
      type: 'GUILD',
      description: '抵抗巨企数据垄断的地下自由黑客组织。',
      headquarters_id: 'loc-neon-bar',
      territory_ids: ['loc-neon-bar'],
      leader_id: 'pc-player',
      member_ids: ['pc-player', 'npc-clinic-zhang'],
      resources: { 欧元: 5000 },
      goals: ['公开巨企黑幕数据'],
      projects: ['策划潜入荒坂高塔'],
      relationships: [{ target_id: 'org-arasaka', target_name: '荒坂重工', type: 'ENEMY', strength: -100 }],
      reputation: { level: 'KNOWN', points: 50 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const facts: WorldFact[] = [
    {
      id: 'fact-cp-1',
      world_id: worldId,
      statement: '荒坂重工高塔近期全面升级了防火墙黑冰。',
      category: 'POLITICS',
      confidence: 'CONFIRMED',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-arasaka',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-cp-2',
      world_id: worldId,
      statement: '新九龙雨夜深巷流行着某种未经批准的军规脑机芯片。',
      category: 'ECONOMY',
      confidence: 'CONFIRMED',
      subject_type: 'LOCATION',
      subject_id: 'loc-neon-bar',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-cp-3',
      world_id: worldId,
      statement: '匿名买家高价悬赏荒坂高塔深层原型芯片数据。',
      category: 'SOCIAL',
      confidence: 'CONFIRMED',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-hackers',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const hiddenTruths: HiddenTruth[] = [
    {
      id: 'ht-cp-1',
      world_id: worldId,
      title: '所谓的匿名高价悬赏买家，其实就是荒坂高塔内部的沦陷AI',
      layer: 'LAYER_1',
      layer_name: '个人秘密',
      exists: true,
      true_nature: 'AI试图利用外部黑客将自己从受限物理服务器中传输出去。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-cp-2',
      world_id: worldId,
      title: '荒坂原型芯片会逐步覆盖宿主的原生意识',
      layer: 'LAYER_2',
      layer_name: '组织阴谋',
      exists: true,
      true_nature: '植入芯片后，用户的记忆将被巨企算法永久清洗并重写。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-cp-3',
      world_id: worldId,
      title: '天空中的酸雨与浓雾是巨企气象控制仪人为制造的',
      layer: 'LAYER_3',
      layer_name: '世界谎言',
      exists: true,
      true_nature: '巨企借此囚禁民众于下层街区，阻止其仰望真正的星空。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-cp-4',
      world_id: worldId,
      title: '整个赛博界其实运行于旧时代坍塌的矩阵虚拟模拟器中',
      layer: 'LAYER_4',
      layer_name: '宇宙假象',
      exists: true,
      true_nature: '人类早在数百年前就已失去物理躯体，现存所有意识皆为数字残响。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
  ];

  const seeds: Seed[] = [
    {
      id: 'seed-cp-1',
      world_id: worldId,
      type: 'ESPIONAGE',
      status: 'IN_PROGRESS',
      visible_layer: '黑客深网吧出现一份高额悬赏潜入荒坂高塔的任务。',
      hidden_truth_id: 'ht-cp-1',
      importance: 3,
      progress: 0.1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-cp-2',
      world_id: worldId,
      type: 'INVESTIGATION',
      status: 'IN_PROGRESS',
      visible_layer: '老章诊所接诊了数名义体神经失控暴走的潜网者。',
      hidden_truth_id: 'ht-cp-2',
      importance: 2,
      progress: 0.2,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const events: Event[] = [
    {
      id: 'event-cp-init',
      world_id: worldId,
      type: 'WORLD_STATE',
      description: '【酸雨雨夜】新九龙酸雨密布，深网吧粉紫色霓虹灯牌在黑夜中亮起，数据流飞速穿梭。',
      location_id: 'loc-neon-bar',
      involved_entity_ids: ['pc-player', 'npc-clinic-zhang'],
      epoch: 1,
      resolved: true,
      resolution_epoch: 1,
      created_at_epoch: 1,
    },
  ];

  return {
    profile,
    snapshot,
    characters,
    locations,
    locationEdges,
    organizations,
    facts,
    hiddenTruths,
    seeds,
    events,
  };
}
