import { WorldTemplate } from '../worldProfile/worldTemplateTypes';
import { WorldProfile } from '../worldProfile/worldProfileTypes';
import {
  WorldSnapshot,
  Character,
  Location,
  LocationEdge,
  Organization,
  WorldFact,
  HiddenTruth,
  Seed,
  Event,
} from '../../types';

export function createSteamArcaneWorldTemplate(worldId: string): WorldTemplate {
  const profile: WorldProfile = {
    world_id: worldId,
    genre: 'STEAM_ARCANUM',
    genre_version: 1,
    display_name: '艾尔德兰',
    world_description: '蒸汽高炉吐着黑烟，魔导机关与古老符文在齿轮交错中轰鸣。',
    cosmology: '魔导以太流转于地壳之下，巨型蒸汽飞艇与机械齿轮构建凡世帝国。',
    power_system: '魔导机械、元素炼金、精金构装、以太回路。',
    social_structure: '帝国王室、魔导师议会、雇佣兵公会、黑鸦商会、圣光守卫团。',
    economy_system: '金币与银币，以太精晶作为工业核心战略资源。',
    geography_style: '雾都城关、机械高塔、黑烟矿井、微光地下城、巨石遗迹。',
    currency_name: '金币',
    energy_name: '以太',
    narrator_role: '地下城主',
    narration_style: '蒸汽朋克与暗黑魔幻交叉，沉重机械感与以太微光。',
    profession_lexicon: ['雇佣兵', '魔导师', '炼金术士', '构装机械师', '圣骑士', '赏金猎人'],
    faction_lexicon: ['红叶雇佣兵酒馆', '圣光守卫团', '黑鸦商会', '魔导师议会'],
    location_lexicon: ['红叶酒馆', '铁冠城下城区', '蒸汽高炉厂', '以太矿洞'],
    creature_lexicon: ['精金构装体', '以太魔物', '发条机械犬', '地底变异兽'],
    item_lexicon: ['金币', '精金战锤', '以太药剂', '蒸汽连发枪', '魔导手枪', '黑麦啤酒'],
    allowed_concepts: [
      '蒸汽', '煤烟', '魔导', '雇佣兵', '骑士', '金币', '以太', '构装', '黑麦啤酒', '高炉'
    ],
    forbidden_concepts: [
      '灵石', '灵力', '宗门', '坊市', '散修', '元婴', '筑基', '飞剑', '乾坤袋',
      '赛博黑客', '黑客', '超音速战机', '核辐射', '辐射废土'
    ],
    default_player_origin: '老牌雇佣兵',
    default_player_title: '雇佣兵客卿',
    created_at_epoch: 1,
    updated_at_epoch: 1,
  };

  const snapshot: WorldSnapshot = {
    id: worldId,
    epoch: 1,
    created_at: new Date().toISOString(),
    world_name: '艾尔德兰',
    world_description: '蒸汽高炉吐着黑烟，魔导机关与古老符文在齿轮交错中轰鸣。',
    world_creation_state: 'CREATED',
    seed: 1234,
    world_facts_count: 3,
    characters_count: 4,
    organizations_count: 3,
    locations_count: 3,
    active_seeds_count: 3,
    frozen_objects_count: 0,
    completed_epochs: 0,
  };

  const locations: Location[] = [
    {
      id: 'loc-tavern',
      world_id: worldId,
      name: '红叶酒馆',
      type: 'TOWN',
      description: '位于铁冠城下城区的雇佣兵酒馆，空气中弥漫着黑麦啤酒与蒸汽机油的气味。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-iron-city'],
      population: 50,
      population_trend: 'STABLE',
      economy: { primary_industry: 'TRADE', wealth_level: 'MEDIUM', trade_volume: 'ACTIVE' },
      security: { crime_rate: 0.4, guard_presence: 'LOW', danger_level: 'SAFE' },
      active_events: [],
      features: ['黑麦啤酒', '悬赏板'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-iron-city',
      world_id: worldId,
      name: '铁冠城下城区',
      type: 'CITY',
      description: '庞大的蒸汽工业城市，管道纵横，高炉吐着浓浓黑烟。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-tavern', 'loc-ether-mine'],
      population: 5000,
      population_trend: 'STABLE',
      economy: { primary_industry: 'INDUSTRY', wealth_level: 'MEDIUM', trade_volume: 'HIGH' },
      security: { crime_rate: 0.5, guard_presence: 'MEDIUM', danger_level: 'SAFE' },
      active_events: [],
      features: ['工业高炉', '机械市场'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-ether-mine',
      world_id: worldId,
      name: '以太矿洞',
      type: 'CAVE',
      description: '城郊开采魔导以太精晶的深层废弃矿井，隐隐有失控构装体游荡。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-iron-city'],
      population: 10,
      population_trend: 'DECLINING',
      economy: { primary_industry: 'INDUSTRY', wealth_level: 'POOR', trade_volume: 'NONE' },
      security: { crime_rate: 0.8, guard_presence: 'NONE', danger_level: 'HAZARDOUS' },
      active_events: [],
      features: ['以太精晶', '失控构装体'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const locationEdges: LocationEdge[] = [
    {
      id: 'edge-steam-1',
      world_id: worldId,
      from_location_id: 'loc-tavern',
      to_location_id: 'loc-iron-city',
      distance: 1.0,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-steam-2',
      world_id: worldId,
      from_location_id: 'loc-iron-city',
      to_location_id: 'loc-tavern',
      distance: 1.0,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-steam-3',
      world_id: worldId,
      from_location_id: 'loc-iron-city',
      to_location_id: 'loc-ether-mine',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-steam-4',
      world_id: worldId,
      from_location_id: 'loc-ether-mine',
      to_location_id: 'loc-iron-city',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
  ];

  const characters: Character[] = [
    {
      id: 'pc-player',
      world_id: worldId,
      type: 'PC',
      name: '卡尔',
      title: '雇佣兵客卿',
      species: '人类',
      age: 26,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-tavern',
      goal: { primary: '解开父亲在以太矿洞失踪之谜' },
      personality: { trait: '冷酷干练', tone: '直截了当' },
      fear: { primary: '被蒸汽机械异化' },
      attributes: { hp: 100, mp: 30, strength: 14, dexterity: 12, intelligence: 10, charisma: 10 },
      skills: ['精金战锤术', '蒸汽枪械打靶'],
      resources: { 金币: 50 },
      inventory: ['精金短锤', '魔导手枪', '皮质护甲'],
      knowledge: ['下城区街道地图'],
      memory: ['在红叶酒馆接下了寻找以太矿洞遗物的悬赏。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在酒馆角落擦拭战锤' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-maria',
      world_id: worldId,
      type: 'NPC',
      name: '玛丽亚',
      title: '红叶酒馆老板娘',
      species: '人类',
      age: 34,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-tavern',
      goal: { primary: '保护酒馆，暗中传递情报' },
      personality: { trait: '机敏泼辣', tone: '热情中带防备' },
      fear: { primary: '黑鸦商会毁掉酒馆' },
      attributes: { hp: 90, mp: 40, strength: 10, dexterity: 13, intelligence: 14, charisma: 15 },
      skills: ['情报收集', '短弩精准'],
      resources: { 金币: 200 },
      inventory: ['袖珍魔导弩', '酒馆账本'],
      knowledge: ['黑鸦商会走私路线'],
      memory: ['卡尔经常在酒馆寻找高风险任务。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在柜台调配黑麦啤酒' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-elton',
      world_id: worldId,
      type: 'NPC',
      name: '埃尔顿',
      title: '圣光守卫团长',
      species: '人类',
      age: 42,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-iron-city',
      goal: { primary: '扫除下城区的非法以太交易' },
      personality: { trait: '刚正不阿', tone: '严厉整饬' },
      fear: { primary: '教会受到腐蚀' },
      attributes: { hp: 160, mp: 60, strength: 16, dexterity: 10, intelligence: 12, charisma: 14 },
      skills: ['圣光封印', '重装铠甲格斗'],
      resources: { 金币: 500 },
      inventory: ['圣光大剑', '守卫团徽章'],
      knowledge: ['下城区黑市据点'],
      memory: ['对黑鸦商会展开例行搜查。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在下城区主干道带队巡逻' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-black-crow-boss',
      world_id: worldId,
      type: 'NPC',
      name: '黑鸦头领',
      title: '黑鸦商会分头领',
      species: '人类',
      age: 39,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-iron-city',
      goal: { primary: '走私以太精晶赚取暴利' },
      personality: { trait: '阴险贪婪', tone: '压低声音' },
      fear: { primary: '被圣光守卫团抓获' },
      attributes: { hp: 110, mp: 50, strength: 11, dexterity: 14, intelligence: 13, charisma: 11 },
      skills: ['暗器毒刃', '走私运货'],
      resources: { 金币: 1000 },
      inventory: ['毒刃', '以太走私契约'],
      knowledge: ['以太矿洞秘密出口'],
      memory: ['成功走私了一批未加工以太精晶。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在暗巷与走私贩商议' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const organizations: Organization[] = [
    {
      id: 'org-mercenary-guild',
      world_id: worldId,
      name: '红叶雇佣兵酒馆公会',
      type: 'GUILD',
      description: '下城区最大的自由雇佣兵组织。',
      headquarters_id: 'loc-tavern',
      territory_ids: ['loc-tavern'],
      leader_id: 'npc-maria',
      member_ids: ['pc-player', 'npc-maria'],
      resources: { 金币: 3000 },
      goals: ['赚取赏金', '保障成员安全'],
      projects: ['悬赏清理以太矿洞'],
      relationships: [],
      reputation: { level: 'KNOWN', points: 40 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-holy-guard',
      world_id: worldId,
      name: '圣光守卫团',
      type: 'MILITIA',
      description: '维护铁冠城秩序的官方宗教武装。',
      headquarters_id: 'loc-iron-city',
      territory_ids: ['loc-iron-city'],
      leader_id: 'npc-elton',
      member_ids: ['npc-elton'],
      resources: { 金币: 20000 },
      goals: ['打击走私', '维系圣光信仰'],
      projects: ['下城区严格戒严'],
      relationships: [{ target_id: 'org-black-crow', target_name: '黑鸦商会', type: 'ENEMY', strength: -90 }],
      reputation: { level: 'RENOWNED', points: 80 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-black-crow',
      world_id: worldId,
      name: '黑鸦商会',
      type: 'CORPORATION',
      description: '控制下城区走私与地下黑市的庞大商会。',
      headquarters_id: 'loc-iron-city',
      territory_ids: ['loc-iron-city', 'loc-ether-mine'],
      leader_id: 'npc-black-crow-boss',
      member_ids: ['npc-black-crow-boss'],
      resources: { 金币: 15000 },
      goals: ['垄断以太走私'],
      projects: ['发掘以太矿洞深层'],
      relationships: [{ target_id: 'org-holy-guard', target_name: '圣光守卫团', type: 'ENEMY', strength: -90 }],
      reputation: { level: 'INFAMOUS', points: -60 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const facts: WorldFact[] = [
    {
      id: 'fact-st-1',
      world_id: worldId,
      statement: '铁冠城下城区的以太供能系统正面临能源短缺。',
      category: 'ECONOMY',
      confidence: 'CONFIRMED',
      subject_type: 'LOCATION',
      subject_id: 'loc-iron-city',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-st-2',
      world_id: worldId,
      statement: '圣光守卫团正在搜查黑鸦商会走私以太精晶的据点。',
      category: 'POLITICS',
      confidence: 'CONFIRMED',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-holy-guard',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-st-3',
      world_id: worldId,
      statement: '以太矿洞深处发现了古代魔导构装体遗迹。',
      category: 'HISTORY',
      confidence: 'RUMOR',
      subject_type: 'LOCATION',
      subject_id: 'loc-ether-mine',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const hiddenTruths: HiddenTruth[] = [
    {
      id: 'ht-st-1',
      world_id: worldId,
      title: '以太矿洞塌方并非意外，而是黑鸦商会引爆了过度抽取装置',
      layer: 'LAYER_1',
      layer_name: '个人秘密',
      exists: true,
      true_nature: '为了独占失控构装体背后的核心核心，商会故意引发了塌方封锁。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-st-2',
      world_id: worldId,
      title: '魔导师议会高层暗中资助黑鸦商会走私',
      layer: 'LAYER_2',
      layer_name: '组织阴谋',
      exists: true,
      true_nature: '议会需要非官方渠道获取禁忌以太精晶进行人体机械构装实验。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-st-3',
      world_id: worldId,
      title: '蒸汽高炉排放的黑烟正在侵蚀凡人灵魂',
      layer: 'LAYER_3',
      layer_name: '世界谎言',
      exists: true,
      true_nature: '所谓的工业副产品废气，实为炼金提纯时散发的以太毒雾。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-st-4',
      world_id: worldId,
      title: '艾尔德兰大地深处的以太核心即将彻底干涸',
      layer: 'LAYER_4',
      layer_name: '宇宙假象',
      exists: true,
      true_nature: '魔导文明的过度开采已使世界本源走向崩溃不可逆倒计时。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
  ];

  const seeds: Seed[] = [
    {
      id: 'seed-st-1',
      world_id: worldId,
      type: 'INVESTIGATION',
      status: 'IN_PROGRESS',
      visible_layer: '红叶酒馆悬赏调查以太矿洞异响。',
      hidden_truth_id: 'ht-st-1',
      importance: 2,
      progress: 0.1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-st-2',
      world_id: worldId,
      type: 'AMBUSH',
      status: 'IN_PROGRESS',
      visible_layer: '黑鸦商会在暗巷运输秘密货物。',
      hidden_truth_id: 'ht-st-2',
      importance: 3,
      progress: 0.2,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-st-3',
      world_id: worldId,
      type: 'CONSTRUCTION',
      status: 'IN_PROGRESS',
      visible_layer: '铁冠城下城区高炉即将启动新一期魔导加压。',
      importance: 1,
      progress: 0.0,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const events: Event[] = [
    {
      id: 'event-st-init',
      world_id: worldId,
      type: 'WORLD_STATE',
      description: '【工业轰鸣】铁冠城下城区的蒸汽高炉轰鸣不断，黑麦啤酒与机油味在红叶酒馆散开。',
      location_id: 'loc-tavern',
      involved_entity_ids: ['pc-player', 'npc-maria'],
      epoch: 1,
      resolved: true,
      resolution_epoch: 1,
      created_at_epoch: 1,
    },
  ];

  return {
    profile,
    snapshot,
    characters,
    locations,
    locationEdges,
    organizations,
    facts,
    hiddenTruths,
    seeds,
    events,
  };
}
