import { WorldTemplate } from '../worldProfile/worldTemplateTypes';
import { WorldProfile } from '../worldProfile/worldProfileTypes';
import {
  WorldSnapshot,
  Character,
  Location,
  LocationEdge,
  Organization,
  WorldFact,
  HiddenTruth,
  Seed,
  Event,
} from '../../types';

export function createWastelandWorldTemplate(worldId: string): WorldTemplate {
  const profile: WorldProfile = {
    world_id: worldId,
    genre: 'WASTELAND',
    genre_version: 1,
    display_name: '废土废墟',
    world_description: '核冬后的黄沙荒漠，坍塌的钢铁地堡，辐射狂暴者与瓶盖交易者。',
    cosmology: '旧文明在核火中化为灰烬，废土幸存者在废墟中苟延残喘。',
    power_system: '废土改枪、变异基因、战术机甲残骸、辐射抗体。',
    social_structure: '废土聚落、掠夺者军阀、拾荒者联盟、钢之兄弟会。',
    economy_system: '瓶盖、纯净水、净水芯片与弹药。',
    geography_style: '黄沙荒漠、破败地堡、辐射坑、废弃机场、荒野加油站。',
    currency_name: '瓶盖',
    energy_name: '燃油核电池',
    narrator_role: '废土记录者',
    narration_style: '粗粝沉重、末日荒凉、生存抉择。',
    profession_lexicon: ['拾荒者', '废土枪手', '废品机械师', '变异猎人', '掠夺者', '守卫者'],
    faction_lexicon: ['钢铁兄弟会', '荒野掠夺者', '绿洲拾荒互助会'],
    location_lexicon: ['黄沙镇', '73号地堡废墟', '辐射沙丘', '废弃加油站'],
    creature_creatures: ['辐射巨蝎', '变异狂暴犬', '废土辐射人', '沙暴狂徒'],
    creature_lexicon: ['辐射巨蝎', '变异狂暴犬', '废土辐射人', '沙暴狂徒'],
    item_lexicon: ['瓶盖', '纯净水', '铁管步枪', '抗辐射药', '罐头肉', '核电池'],
    allowed_concepts: [
      '废土', '瓶盖', '辐射', '拾荒', '纯净水', '地堡', '变异', '黄沙', '掠夺者'
    ],
    forbidden_concepts: [
      '灵石', '灵力', '宗门', '坊市', '散修', '元婴', '筑基', '飞剑', '乾坤袋',
      '雇佣兵酒馆', '魔导师', '骑士团', '黑麦啤酒', '精金战锤', '赛博黑客', '深网'
    ],
    default_player_origin: '地堡出身的独行拾荒者',
    default_player_title: '荒野浪客',
    created_at_epoch: 1,
    updated_at_epoch: 1,
  };

  const snapshot: WorldSnapshot = {
    id: worldId,
    epoch: 1,
    created_at: new Date().toISOString(),
    world_name: '废土废墟',
    world_description: '核冬后的黄沙荒漠，坍塌的钢铁地堡，辐射狂暴者与瓶盖交易者。',
    world_creation_state: 'CREATED',
    seed: 7777,
    world_facts_count: 3,
    characters_count: 3,
    organizations_count: 2,
    locations_count: 3,
    active_seeds_count: 2,
    frozen_objects_count: 0,
    completed_epochs: 0,
  };

  const locations: Location[] = [
    {
      id: 'loc-wasteland-town',
      world_id: worldId,
      name: '黄沙聚落',
      type: 'TOWN',
      description: '用破烂铁皮与汽车废壳围建的荒漠小镇，幸存者在此用瓶盖换取纯净水与抗辐射药。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-bunker-73'],
      population: 80,
      population_trend: 'STABLE',
      economy: { primary_industry: 'TRADE', wealth_level: 'POOR', trade_volume: 'MEDIUM' },
      security: { crime_rate: 0.5, guard_presence: 'LOW', danger_level: 'SAFE' },
      active_events: [],
      features: ['水泵净水站', '瓶盖交易所'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-bunker-73',
      world_id: worldId,
      name: '73号地堡废墟',
      type: 'DUNGEON',
      description: '半埋在黄沙下的旧时代地下防核避难所，防爆门已被破坏，深处散发着淡黄色辐射荧光。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-wasteland-town', 'loc-radiation-dunes'],
      population: 5,
      population_trend: 'DECLINING',
      economy: { primary_industry: 'INDUSTRY', wealth_level: 'WEALTHY', trade_volume: 'NONE' },
      security: { crime_rate: 0.8, guard_presence: 'NONE', danger_level: 'HAZARDOUS' },
      active_events: [],
      features: ['旧时代战术装备', '强辐射区域'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-radiation-dunes',
      world_id: worldId,
      name: '辐射黄沙丘',
      type: 'MOUNTAIN',
      description: '风沙呼啸的死寂沙丘，埋葬着大量旧时代汽车与变异巨蝎巢穴。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-bunker-73'],
      population: 0,
      population_trend: 'STABLE',
      economy: { primary_industry: 'AGRICULTURE', wealth_level: 'POOR', trade_volume: 'NONE' },
      security: { crime_rate: 0.9, guard_presence: 'NONE', danger_level: 'DEADLY' },
      active_events: [],
      features: ['辐射风暴', '巨蝎巢穴'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const locationEdges: LocationEdge[] = [
    {
      id: 'edge-wl-1',
      world_id: worldId,
      from_location_id: 'loc-wasteland-town',
      to_location_id: 'loc-bunker-73',
      distance: 2.5,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-wl-2',
      world_id: worldId,
      from_location_id: 'loc-bunker-73',
      to_location_id: 'loc-wasteland-town',
      distance: 2.5,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-wl-3',
      world_id: worldId,
      from_location_id: 'loc-bunker-73',
      to_location_id: 'loc-radiation-dunes',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-wl-4',
      world_id: worldId,
      from_location_id: 'loc-radiation-dunes',
      to_location_id: 'loc-bunker-73',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
  ];

  const characters: Character[] = [
    {
      id: 'pc-player',
      world_id: worldId,
      type: 'PC',
      name: '狂沙',
      title: '荒野浪客',
      species: '人类',
      age: 27,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-wasteland-town',
      goal: { primary: '进入73号地堡寻找未损坏的净水芯片' },
      personality: { trait: '警惕坚韧', tone: '话少干脆' },
      fear: { primary: '严重辐射导致基因崩溃' },
      attributes: { hp: 100, mp: 20, strength: 13, dexterity: 12, intelligence: 11, charisma: 9 },
      skills: ['铁管步枪射击', '废品机械拆卸'],
      resources: { 瓶盖: 40, 纯净水: 5 },
      inventory: ['铁管步枪', '抗辐射药一针', '风沙护目镜'],
      knowledge: ['黄沙废土安全路线'],
      memory: ['在黄沙聚落听说73号地堡有净水芯片遗存。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在黄沙聚落水泵前清点瓶盖' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-water-merchant',
      world_id: worldId,
      type: 'NPC',
      name: '老巴克',
      title: '聚落水商人',
      species: '人类',
      age: 58,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-wasteland-town',
      goal: { primary: '掌控黄沙聚落唯一的水泵' },
      personality: { trait: '守财贪婪', tone: '咳嗽沙哑' },
      fear: { primary: '掠夺者强占水泵' },
      attributes: { hp: 80, mp: 10, strength: 8, dexterity: 9, intelligence: 13, charisma: 12 },
      skills: ['水质过滤', '瓶盖鉴伪'],
      resources: { 瓶盖: 600, 纯净水: 100 },
      inventory: ['双管猎枪', '聚落账本'],
      knowledge: ['地堡净水系统结构'],
      memory: ['雇佣狂沙前往地堡搜寻零部件。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在水泵房前卖纯净水' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-raider-boss',
      world_id: worldId,
      type: 'NPC',
      name: '独眼刀疤',
      title: '荒野掠夺者头领',
      species: '人类（轻度变异）',
      age: 35,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-bunker-73',
      goal: { primary: '洗劫黄沙聚落的水源' },
      personality: { trait: '残忍凶暴', tone: '咆哮狂妄' },
      fear: { primary: '被更强强的废土军阀吞并' },
      attributes: { hp: 150, mp: 10, strength: 16, dexterity: 11, intelligence: 9, charisma: 10 },
      skills: ['砍刀重击', '废土改装车驾驶'],
      resources: { 瓶盖: 300 },
      inventory: ['锯齿大砍刀', '皮质铆钉甲'],
      knowledge: ['辐射沙丘陷阱布置'],
      memory: ['带领掠夺者占据了73号地堡外层。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在地堡入口分发弹药' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const organizations: Organization[] = [
    {
      id: 'org-scavengers',
      world_id: worldId,
      name: '绿洲拾荒互助会',
      type: 'GUILD',
      description: '废土幸存者组建的互助交易联盟。',
      headquarters_id: 'loc-wasteland-town',
      territory_ids: ['loc-wasteland-town'],
      leader_id: 'npc-water-merchant',
      member_ids: ['pc-player', 'npc-water-merchant'],
      resources: { 瓶盖: 2000 },
      goals: ['保卫聚落水泵', '联合拾荒抵抗掠夺者'],
      projects: ['搜寻73号地堡'],
      relationships: [{ target_id: 'org-raiders', target_name: '荒野掠夺者', type: 'ENEMY', strength: -100 }],
      reputation: { level: 'KNOWN', points: 50 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-raiders',
      world_id: worldId,
      name: '荒野掠夺者',
      type: 'MILITIA',
      description: '依靠洗劫其他聚落维生的废土悍匪。',
      headquarters_id: 'loc-bunker-73',
      territory_ids: ['loc-bunker-73', 'loc-radiation-dunes'],
      leader_id: 'npc-raider-boss',
      member_ids: ['npc-raider-boss'],
      resources: { 瓶盖: 1000 },
      goals: ['强占水泵与废墟资源'],
      projects: ['筹备进攻黄沙聚落'],
      relationships: [{ target_id: 'org-scavengers', target_name: '绿洲拾荒互助会', type: 'ENEMY', strength: -100 }],
      reputation: { level: 'INFAMOUS', points: -80 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const facts: WorldFact[] = [
    {
      id: 'fact-wl-1',
      world_id: worldId,
      statement: '黄沙聚落的水泵是方圆百里唯一稳定的地下淡水来源。',
      category: 'ECONOMY',
      confidence: 'CONFIRMED',
      subject_type: 'LOCATION',
      subject_id: 'loc-wasteland-town',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-wl-2',
      world_id: worldId,
      statement: '荒野掠夺者正在73号地堡废墟集结弹药。',
      category: 'POLITICS',
      confidence: 'CONFIRMED',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-raiders',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-wl-3',
      world_id: worldId,
      statement: '73号地堡深处仍保存着旧时代的军用净化芯片。',
      category: 'HISTORY',
      confidence: 'RUMOR',
      subject_type: 'LOCATION',
      subject_id: 'loc-bunker-73',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const hiddenTruths: HiddenTruth[] = [
    {
      id: 'ht-wl-1',
      world_id: worldId,
      title: '老巴克的纯净水里掺杂了低剂量微量辐射净化沉淀剂',
      layer: 'LAYER_1',
      layer_name: '个人秘密',
      exists: true,
      true_nature: '沉淀剂长期饮用会导致居民产生轻度依赖，无法离开聚落。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-wl-2',
      world_id: worldId,
      title: '73号地堡当年并非核打击毁坏，而是内部发生了生物遗传变异失控',
      layer: 'LAYER_2',
      layer_name: '组织阴谋',
      exists: true,
      true_nature: '旧时代地堡科学家将全体居民作为抗辐射基因突变实验体。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-wl-3',
      world_id: worldId,
      title: '天空中的辐射风暴是有节奏地由远古防空轨道卫星释放的',
      layer: 'LAYER_3',
      layer_name: '世界谎言',
      exists: true,
      true_nature: '废土气候受到失控防空防御网的自动化气象干预。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-wl-4',
      world_id: worldId,
      title: '大地地核深处早已净化完成，表面废土系人为维持的隔离实验场',
      layer: 'LAYER_4',
      layer_name: '宇宙假象',
      exists: true,
      true_nature: '地底深处的纯净新人类文明一直在观察地面废土幸存者的演化。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
  ];

  const seeds: Seed[] = [
    {
      id: 'seed-wl-1',
      world_id: worldId,
      type: 'INVESTIGATION',
      status: 'IN_PROGRESS',
      visible_layer: '老巴克悬赏前往73号地堡寻找净化芯片。',
      hidden_truth_id: 'ht-wl-1',
      importance: 3,
      progress: 0.1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-wl-2',
      world_id: worldId,
      type: 'RAID',
      status: 'IN_PROGRESS',
      visible_layer: '荒野掠夺者侦察兵频频在黄沙聚落外围活动。',
      importance: 2,
      progress: 0.2,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const events: Event[] = [
    {
      id: 'event-wl-init',
      world_id: worldId,
      type: 'WORLD_STATE',
      description: '【废土风沙】风沙刮过黄沙聚落的铁皮屋顶，水泵发出刺耳的轰鸣，瓶盖在铁皮柜台敲响。',
      location_id: 'loc-wasteland-town',
      involved_entity_ids: ['pc-player', 'npc-water-merchant'],
      epoch: 1,
      resolved: true,
      resolution_epoch: 1,
      created_at_epoch: 1,
    },
  ];

  return {
    profile,
    snapshot,
    characters,
    locations,
    locationEdges,
    organizations,
    facts,
    hiddenTruths,
    seeds,
    events,
  };
}
