import { WorldTemplate } from '../worldProfile/worldTemplateTypes';
import { WorldProfile } from '../worldProfile/worldProfileTypes';
import {
  WorldSnapshot,
  Character,
  Location,
  LocationEdge,
  Organization,
  WorldFact,
  HiddenTruth,
  Seed,
  Event,
} from '../../types';

export function createXianxiaWorldTemplate(worldId: string): WorldTemplate {
  const profile: WorldProfile = {
    world_id: worldId,
    genre: 'XIANXIA',
    genre_version: 1,
    display_name: '苍穹道界',
    world_description: '灵脉复苏，宗门林立，散修聚集于坊市，仙魔争锋，古修秘境异动。',
    cosmology: '九天十地，诸天三千道界，天道法则运行不息。',
    power_system: '炼气、筑基、金丹、元婴、化神境界体系；剑、丹、符、阵、体修等大道。',
    social_structure: '名门正派、魔道盟会、世家望族、散修联盟、仙城坊市。',
    economy_system: '以灵石为基础货币，丹药、法器、符箓与灵药为通货。',
    geography_style: '仙山福地、悬浮洞府、灵脉大河、瘴气蛮荒、幽冥秘境。',
    currency_name: '灵石',
    energy_name: '灵力',
    narrator_role: '天道演算者',
    narration_style: '古意、克制、清晰，不堆砌晦涩辞藻',
    profession_lexicon: ['散修', '剑客', '丹师', '符修', '阵修', '体修', '御兽师', '掌柜', '执事'],
    faction_lexicon: ['太虚剑宗', '九幽魔盟', '青河散修会'],
    location_lexicon: ['云来客栈', '青河坊市', '雾隐灵林', '玄真古洞'],
    creature_lexicon: ['灵兽', '妖兽', '剑灵', '魔修'],
    item_lexicon: ['灵石', '旧木剑', '聚气散', '乾坤袋', '下品灵石', '筑基丹', '飞剑', '符箓'],
    allowed_concepts: [
      '灵脉', '宗门', '坊市', '散修', '仙魔', '妖兽', '秘境', '丹药', '符箓', '阵法', '飞剑', '体修',
      '气血', '灵力', '根骨', '身法', '悟性', '气度', '灵石', '乾坤袋', '天道', '天劫', '古修'
    ],
    forbidden_concepts: [
      '雇佣兵公会', '雇佣兵', '魔导师', '骑士团', '骑士', '蒸汽锅炉', '蒸汽', '黑麦啤酒', '地下城主',
      'MP 药剂', '精金构装战锤', '精金', '构装', '工业革命', '赛博黑客', '黑客', '枪斗术', '枪械',
      '核辐射', '艾尔德兰', '红叶雇佣兵酒馆', '红叶酒馆', '铁冠城', '圣光守卫团', '黑鸦商会',
      '卡尔', '玛丽亚', '埃尔顿'
    ],
    default_player_origin: '无门无派的初入道途者',
    default_player_title: '未知修士',
    created_at_epoch: 1,
    updated_at_epoch: 1,
  };

  const snapshot: WorldSnapshot = {
    id: worldId,
    epoch: 1,
    created_at: new Date().toISOString(),
    world_name: '苍穹道界',
    world_description: '灵脉复苏，宗门林立，散修聚集于坊市，仙魔争锋，古修秘境异动。',
    world_creation_state: 'CREATED',
    seed: 8888,
    world_facts_count: 3,
    characters_count: 6,
    organizations_count: 3,
    locations_count: 4,
    active_seeds_count: 5,
    frozen_objects_count: 0,
    completed_epochs: 0,
  };

  const locations: Location[] = [
    {
      id: 'loc-yunlai-inn',
      world_id: worldId,
      name: '云来客栈',
      type: 'TOWN',
      description: '青河坊市边缘落脚的歇息客栈，檀香缭绕，常有来往散修在此打探消息。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-qinghe-market'],
      population: 40,
      population_trend: 'STABLE',
      economy: { primary_industry: 'TRADE', wealth_level: 'MEDIUM', trade_volume: 'ACTIVE' },
      security: { crime_rate: 0.2, guard_presence: 'LOW', danger_level: 'SAFE' },
      active_events: [],
      features: ['檀香客房', '打探消息'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-qinghe-market',
      world_id: worldId,
      name: '青河坊市',
      type: 'CITY',
      description: '依托地下低阶灵脉建立的散修集市，摆满丹药、符箓与法器残片。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-yunlai-inn', 'loc-mist-spirit-forest'],
      population: 300,
      population_trend: 'GROWING',
      economy: { primary_industry: 'TRADE', wealth_level: 'MEDIUM', trade_volume: 'HIGH' },
      security: { crime_rate: 0.3, guard_presence: 'MEDIUM', danger_level: 'SAFE' },
      active_events: [],
      features: ['灵物交易', '执事榜单'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-mist-spirit-forest',
      world_id: worldId,
      name: '雾隐灵林',
      type: 'FOREST',
      description: '坊市外围灵气浓郁的古林，云雾缭绕，生长着初级灵草，但也潜伏着低阶妖兽。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-qinghe-market', 'loc-ancient-cave'],
      population: 20,
      population_trend: 'STABLE',
      economy: { primary_industry: 'AGRICULTURE', wealth_level: 'POOR', trade_volume: 'LOW' },
      security: { crime_rate: 0.6, guard_presence: 'NONE', danger_level: 'HAZARDOUS' },
      active_events: [],
      features: ['灵草采集', '妖兽出没'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'loc-ancient-cave',
      world_id: worldId,
      name: '玄真古洞',
      type: 'CAVE',
      description: '雾隐灵林深处隐蔽的古修残破洞府，入口被淡蓝色阵法封印，隐隐透露古老禁制波动。',
      status: 'ACTIVE',
      child_ids: [],
      connected_to: ['loc-mist-spirit-forest'],
      population: 0,
      population_trend: 'DECLINING',
      economy: { primary_industry: 'TRADE', wealth_level: 'WEALTHY', trade_volume: 'NONE' },
      security: { crime_rate: 0.8, guard_presence: 'NONE', danger_level: 'DEADLY' },
      active_events: [],
      features: ['古代禁制', '古修遗产'],
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const locationEdges: LocationEdge[] = [
    {
      id: 'edge-inn-market',
      world_id: worldId,
      from_location_id: 'loc-yunlai-inn',
      to_location_id: 'loc-qinghe-market',
      distance: 1.0,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-market-inn',
      world_id: worldId,
      from_location_id: 'loc-qinghe-market',
      to_location_id: 'loc-yunlai-inn',
      distance: 1.0,
      travel_cost: 0,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-market-forest',
      world_id: worldId,
      from_location_id: 'loc-qinghe-market',
      to_location_id: 'loc-mist-spirit-forest',
      distance: 2.0,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-forest-market',
      world_id: worldId,
      from_location_id: 'loc-mist-spirit-forest',
      to_location_id: 'loc-qinghe-market',
      distance: 2.0,
      travel_cost: 1,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-forest-cave',
      world_id: worldId,
      from_location_id: 'loc-mist-spirit-forest',
      to_location_id: 'loc-ancient-cave',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
    {
      id: 'edge-cave-forest',
      world_id: worldId,
      from_location_id: 'loc-ancient-cave',
      to_location_id: 'loc-mist-spirit-forest',
      distance: 3.0,
      travel_cost: 2,
      travel_time_epochs: 1,
      status: 'OPEN',
    },
  ];

  const characters: Character[] = [
    {
      id: 'pc-player',
      world_id: worldId,
      type: 'PC',
      name: '未知修士',
      title: '无门无派的初入道途者',
      species: '人类',
      age: 18,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-yunlai-inn',
      goal: { primary: '寻求长生，破解大道禁锢', secondary: ['探索雾隐灵林', '赚取灵石'] },
      personality: { trait: '坚韧沉稳', tone: '恭敬淡然' },
      fear: { primary: '寿元将尽，身死道消' },
      attributes: { hp: 100, mp: 50, strength: 10, dexterity: 10, intelligence: 10, charisma: 10 },
      skills: ['基础吐纳', '御剑入门'],
      resources: { 灵石: 10, 灵力: 50 },
      inventory: ['旧木剑', '聚气散', '乾坤袋'],
      knowledge: ['青河坊市地图', '基础灵草辨识'],
      memory: ['初入青河坊市，落脚于云来客栈。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在云来客栈内盘膝打坐' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-market-deacon',
      world_id: worldId,
      type: 'NPC',
      name: '赵执事',
      title: '青河坊市执事',
      species: '人类',
      age: 45,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-qinghe-market',
      goal: { primary: '维持坊市秩序，防范魔道渗入' },
      personality: { trait: '威严严谨', tone: '公事公办' },
      fear: { primary: '坊市灵脉受损' },
      attributes: { hp: 150, mp: 100, strength: 14, dexterity: 12, intelligence: 14, charisma: 13 },
      skills: ['青河剑法', '辨灵眼'],
      resources: { 灵石: 120 },
      inventory: ['青锋剑', '执事令牌'],
      knowledge: ['坊市人员变动', '灵脉走向'],
      memory: ['近日注意到散修失踪事件频发。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在坊市外务堂巡查榜单' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-inn-keeper',
      world_id: worldId,
      type: 'NPC',
      name: '陆掌柜',
      title: '云来客栈掌柜',
      species: '人类',
      age: 52,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-yunlai-inn',
      goal: { primary: '和气生财，收集坊市小道消息' },
      personality: { trait: '圆滑老练', tone: '热情周到' },
      fear: { primary: '客栈内发生打斗破坏阵法' },
      attributes: { hp: 80, mp: 30, strength: 8, dexterity: 9, intelligence: 12, charisma: 15 },
      skills: ['算筹术', '察言观色'],
      resources: { 灵石: 80 },
      inventory: ['账本', '下品灵石囊'],
      knowledge: ['过往散修身份', '坊市流言'],
      memory: ['接待了大量准备前往雾隐灵林探险的散修。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在客栈柜台拨打算盘' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-senior-cultivator',
      world_id: worldId,
      type: 'NPC',
      name: '莫老',
      title: '隐姓散修前辈',
      species: '人类',
      age: 68,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-qinghe-market',
      goal: { primary: '隐匿过去身份，安度晚年' },
      personality: { trait: '孤僻冷漠', tone: '语气低沉' },
      fear: { primary: '九幽魔盟追杀者找上门' },
      attributes: { hp: 120, mp: 150, strength: 11, dexterity: 11, intelligence: 16, charisma: 9 },
      skills: ['魔气隐匿', '基础破阵'],
      resources: { 灵石: 50 },
      inventory: ['破旧拂尘', '残破功法玉简'],
      knowledge: ['九幽魔盟内部图谋', '玄真古洞破阵法'],
      memory: ['当年脱离魔盟时带走了一枚洞府钥匙残片。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在坊市角落暗中观察过往修士' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-sect-disciple',
      world_id: worldId,
      type: 'NPC',
      name: '林师兄',
      title: '太虚剑宗外门弟子',
      species: '人类',
      age: 22,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-mist-spirit-forest',
      goal: { primary: '调查灵兽异动原因，立功回宗' },
      personality: { trait: '正气傲然', tone: '自信耿直' },
      fear: { primary: '任务失败被贬为杂役' },
      attributes: { hp: 130, mp: 80, strength: 13, dexterity: 13, intelligence: 11, charisma: 12 },
      skills: ['太虚十三剑', '御风步'],
      resources: { 灵石: 40 },
      inventory: ['太虚佩剑', '回气丹'],
      knowledge: ['宗门剑诀', '雾隐灵林路线'],
      memory: ['奉命入林调查，发现多处妖兽有被魔气侵蚀迹象。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在雾隐灵林边缘戒备' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'npc-alchemist',
      world_id: worldId,
      type: 'NPC',
      name: '柳丹师',
      title: '青河坊市丹师',
      species: '人类',
      age: 38,
      status: 'ALIVE',
      presence_state: 'AT_LOCATION',
      location_id: 'loc-qinghe-market',
      goal: { primary: '搜集雾隐灵草，炼制筑基丹' },
      personality: { trait: '专心致志', tone: '和蔼温平' },
      fear: { primary: '灵草断供导致丹炉炸毁' },
      attributes: { hp: 90, mp: 110, strength: 9, dexterity: 10, intelligence: 15, charisma: 11 },
      skills: ['丹道初解', '控火术'],
      resources: { 灵石: 90 },
      inventory: ['青铜药鼎', '凝气丹三瓶'],
      knowledge: ['丹方药理', '灵草品质判定'],
      memory: ['悬赏征求优质灵雾草。'],
      relationships: [],
      current_action: { action: 'IDLE', description: '在药铺内整理草药' },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const organizations: Organization[] = [
    {
      id: 'org-taixu-sword',
      world_id: worldId,
      name: '太虚剑宗',
      type: 'GUILD',
      description: '方圆千里名门正宗，以太虚剑典名震仙界。',
      headquarters_id: 'loc-qinghe-market',
      territory_ids: ['loc-qinghe-market', 'loc-mist-spirit-forest'],
      leader_id: 'npc-sect-disciple',
      member_ids: ['npc-sect-disciple'],
      resources: { 灵石: 10000, 飞剑: 500 },
      goals: ['维护修仙界秩序', '清除九幽魔盟据点'],
      projects: ['招收外门弟子', '调查灵林魔气'],
      relationships: [{ target_id: 'org-jiuyou-demon', target_name: '九幽魔盟', type: 'ENEMY', strength: -100 }],
      reputation: { level: 'RENOWNED', points: 90 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-jiuyou-demon',
      world_id: worldId,
      name: '九幽魔盟',
      type: 'CULT',
      description: '潜伏于暗处的邪道盟会，擅长血祭与强取灵脉。',
      headquarters_id: 'loc-ancient-cave',
      territory_ids: ['loc-ancient-cave'],
      leader_id: 'npc-senior-cultivator',
      member_ids: [],
      resources: { 灵石: 5000, 魔器: 100 },
      goals: ['破开玄真古洞封印', '夺取地下灵脉'],
      projects: ['暗中搜集血气', '试探古洞禁制'],
      relationships: [{ target_id: 'org-taixu-sword', target_name: '太虚剑宗', type: 'ENEMY', strength: -100 }],
      reputation: { level: 'INFAMOUS', points: -80 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'org-qinghe-cultivators',
      world_id: worldId,
      name: '青河散修会',
      type: 'GUILD',
      description: '青河坊市散修自发建立的互助联盟，互相买卖灵物与组队探险。',
      headquarters_id: 'loc-qinghe-market',
      territory_ids: ['loc-qinghe-market'],
      leader_id: 'npc-market-deacon',
      member_ids: ['npc-market-deacon', 'npc-inn-keeper', 'npc-alchemist'],
      resources: { 灵石: 2000 },
      goals: ['保障散修安全', '公平灵物买卖'],
      projects: ['发布除妖悬赏', '组织进山采药'],
      relationships: [],
      reputation: { level: 'KNOWN', points: 50 },
      frozen: false,
      simulation_level: 1,
      last_simulated_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const facts: WorldFact[] = [
    {
      id: 'fact-xx-1',
      world_id: worldId,
      statement: '青河坊市依托附近低阶灵脉供给灵石与灵药。',
      category: 'ECONOMY',
      confidence: 'CONFIRMED',
      subject_type: 'LOCATION',
      subject_id: 'loc-qinghe-market',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-xx-2',
      world_id: worldId,
      statement: '太虚剑宗正在派员调查雾隐灵林妖兽狂暴原因。',
      category: 'POLITICS',
      confidence: 'CONFIRMED',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-taixu-sword',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'fact-xx-3',
      world_id: worldId,
      statement: '传闻九幽魔盟探子已潜入青河坊市周边寻找古修遗迹。',
      category: 'HISTORY',
      confidence: 'RUMOR',
      subject_type: 'ORGANIZATION',
      subject_id: 'org-jiuyou-demon',
      is_active: true,
      valid_from_epoch: 1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const hiddenTruths: HiddenTruth[] = [
    {
      id: 'ht-layer-1',
      world_id: worldId,
      title: '散修前辈莫老曾是九幽魔盟弃徒',
      layer: 'LAYER_1',
      layer_name: '个人秘密',
      exists: true,
      true_nature: '莫老数十年前因反对血祭被九幽魔盟追杀，逃至坊市隐姓埋名。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-layer-2',
      world_id: worldId,
      title: '九幽魔盟试图血祭坊市灵脉破开古洞',
      layer: 'LAYER_2',
      layer_name: '组织阴谋',
      exists: true,
      true_nature: '魔盟计划在灵潮到来时引动魔气污染灵脉，强行破除玄真古洞禁制。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-layer-3',
      world_id: worldId,
      title: '所谓天劫并非纯粹天道自然法则',
      layer: 'LAYER_3',
      layer_name: '世界谎言',
      exists: true,
      true_nature: '修仙界的元婴天劫已被上界大阵干预，成为绞杀天才修士的收割机制。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
    {
      id: 'ht-layer-4',
      world_id: worldId,
      title: '苍穹道界的飞升通道被古代仙庭人为封锁',
      layer: 'LAYER_4',
      layer_name: '宇宙假象',
      exists: true,
      true_nature: '三千道界通往仙庭的升仙路早在数万年前被仙庭至尊抽离了秩序本源。',
      revealed: false,
      locked_at_epoch: 1,
      immutable: true,
    },
  ];

  const seeds: Seed[] = [
    {
      id: 'seed-xx-1',
      world_id: worldId,
      type: 'INVESTIGATION',
      status: 'IN_PROGRESS',
      visible_layer: '青河坊市数名单独进山采药的散修接连失踪。',
      hidden_truth_id: 'ht-layer-1',
      importance: 2,
      progress: 0.1,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-xx-2',
      world_id: worldId,
      type: 'RAID',
      status: 'IN_PROGRESS',
      visible_layer: '雾隐灵林深处灵气紊乱，低阶妖兽有成群冲击坊市的迹象。',
      hidden_truth_id: 'ht-layer-2',
      importance: 3,
      progress: 0.2,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-xx-3',
      world_id: worldId,
      type: 'FESTIVAL',
      status: 'IN_PROGRESS',
      visible_layer: '太虚剑宗宣布将于下月在青河坊市招募外门弟子。',
      importance: 1,
      progress: 0.0,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-xx-4',
      world_id: worldId,
      type: 'ESPIONAGE',
      status: 'IN_PROGRESS',
      visible_layer: '神秘黑衣修士在坊市暗中高价收购防魔符箓与阵盘。',
      hidden_truth_id: 'ht-layer-2',
      importance: 2,
      progress: 0.15,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
    {
      id: 'seed-xx-5',
      world_id: worldId,
      type: 'RITUAL',
      status: 'IN_PROGRESS',
      visible_layer: '玄真古洞外的淡蓝阵法近夜频频闪烁古怪符文。',
      hidden_truth_id: 'ht-layer-4',
      importance: 4,
      progress: 0.05,
      created_at_epoch: 1,
      updated_at_epoch: 1,
    },
  ];

  const events: Event[] = [
    {
      id: 'event-xx-init',
      world_id: worldId,
      type: 'WORLD_STATE',
      description: '【道历初启】苍穹道界灵潮渐盛，青河坊市外的雾隐灵林近日灵兽躁动。',
      location_id: 'loc-qinghe-market',
      involved_entity_ids: ['pc-player', 'npc-market-deacon'],
      epoch: 1,
      resolved: true,
      resolution_epoch: 1,
      created_at_epoch: 1,
    },
  ];

  return {
    profile,
    snapshot,
    characters,
    locations,
    locationEdges,
    organizations,
    facts,
    hiddenTruths,
    seeds,
    events,
  };
}
